Repository texas-justice-initiative/website-nextjs, pull requests merged in 2021-04, with the labels that each got.

#574 Update Pages “interactive”
  content/interactive.md
Labels: netlify-cms/pending_publish

#578 Update Data Tools “covidDeathsInTexas”
  content/data-tools/covid-deaths-in-texas.md
Labels: netlify-cms/pending_publish

#581 Update Publications “preConvictionDeaths”
  content/publications/pre-conviction-deaths-in-texas-jails.md
Labels: netlify-cms/draft

#582 Update Pages “publications”
  content/publications.md
Labels: netlify-cms/pending_publish

#583 Update Publications “preConvictionDeaths”
  content/publications/pre-conviction-deaths-in-texas-jails.md
Labels: netlify-cms/pending_publish

#563 Update Blog Post “this-is-how-we-watchdog”
  content/blog/posts/this-is-how-we-watchdog.md
Labels: netlify-cms/draft

#562 Create Blog Post “texas-attorney-general’s-sites-for-death-and-shooting-reports-go-dark”
  content/blog/posts/texas-attorney-general’s-sites-for-death-and-shooting-reports-go-dark.md
Labels: netlify-cms/pending_review

#588 Update Pages “interactive”
  content/interactive.md
Labels: netlify-cms/pending_publish

#590 Update Pages “aboutUs”
  content/about-us.md
Labels: netlify-cms/pending_publish

#592 Update Pages “news”
  content/newsfeed.md
Labels: netlify-cms/pending_publish

#595 Update Pages “news”
  content/newsfeed.md
Labels: netlify-cms/pending_publish
