Repository texas-justice-initiative/website-nextjs, pull requests merged in 2021-07, with the labels that each got.

#652 Update Pages “aboutUs”
  content/about-us.md
Labels: netlify-cms/pending_publish

#625 602/global styles
  components/BioBox.js
  components/BlogFeed.js
  components/DataTable.js
  components/DonorThumbnails.js
  components/Footer.js
  components/Header.js
  components/Hero.js
  components/Layout.js
  components/Meta.js
  components/NewsFeed.js
  components/Page.js
  components/PeopleGrid.js
  components/Primary.js
  components/Sidebar.js
  components/VolunteerSurvey.js
  components/charts/chartsjs/ChartNote.js
  components/explore-the-data-page/DatasetDetails.js
  components/explore-the-data-page/FilterPanel.js
  components/forms/DonationForm.js
  components/homepage/HomepageNewsFeed.js
  components/homepage/StateofData.js
  pages/about.js
  pages/contact.js
  pages/datasets/[dataset].js
  pages/index.js
  pages/post/[postname].js
  styles/GlobalStyle.js
  styles/variables/breakpoints.js
  styles/variables/colors.js
  styles/variables/integrations/cloudinary.js
  styles/variables/site.js
  styles/variables/typography.js
  theme.js
Labels: wip

#658 Update Pages “interactive”
  content/interactive.md
Labels: netlify-cms/pending_publish

#659 Update Pages “news”
  content/newsfeed.md
Labels: netlify-cms/pending_publish

#654 Create Blog Post “join-our-team”
  content/blog/posts/join-our-team.md
Labels: netlify-cms/pending_review

#653 Update Pages “volunteer”
  content/volunteer.md
Labels: netlify-cms/pending_review

#669 Update Blog Post “join-our-team”
  content/blog/posts/join-our-team.md
Labels: netlify-cms/pending_publish

#670 Update Blog Post “join-our-team”
  content/blog/posts/join-our-team.md
Labels: netlify-cms/pending_publish

#671 Update Blog Post “join-our-team”
  content/blog/posts/join-our-team.md
Labels: netlify-cms/pending_publish

#672 Update Blog Post “join-our-team”
  content/blog/posts/join-our-team.md
Labels: netlify-cms/pending_publish

#673 Update Components “newContentBanner”
  content/new-content-banner.md
Labels: netlify-cms/pending_publish

#674 Update Pages “news”
  content/newsfeed.md
Labels: netlify-cms/pending_publish
