Repository texas-justice-initiative/website-nextjs, pull requests merged in 2021-01, with the labels that each got.

#507 Create Blog Author “map-name-hongsup-shin-headshot-https-res-cloudinary-com-texas-justice-initiative-image-upload-v1583374725-hongsup-shin_hmegrv-jpg-biography-volunteer-data-scientist-at-tji-twitterusername-hongsupshin-githubusername-hongsups”
  content/blog/authors/map-name-hongsup-shin-headshot-https-res-cloudinary-com-texas-justice-initiative-image-upload-v1583374725-hongsup-shin_hmegrv-jpg-biography-volunteer-data-scientist-at-tji-twitterusername-hongsupshin-githubusername-hongsups.md
Labels: netlify-cms/pending_publish

#506 Create Blog Author “map-headshot-https-res-cloudinary-com-texas-justice-initiative-image-upload-v1583374725-hongsup-shin_hmegrv-jpg-name-hongsup-shin-biography-volunteer-data-scientist-at-tji-twitterusername-hongsupshin-githubusername-hongsups”
  content/blog/authors/map-headshot-https-res-cloudinary-com-texas-justice-initiative-image-upload-v1583374725-hongsup-shin_hmegrv-jpg-name-hongsup-shin-biography-volunteer-data-scientist-at-tji-twitterusername-hongsupshin-githubusername-hongsups.md
Labels: netlify-cms/draft

#508 Update Blog Author “map-name-hongsup-shin-headshot-https-res-cloudinary-com-texas-justice-initiative-image-upload-v1583374725-hongsup-shin_hmegrv-jpg-biography-volunteer-data-scientist-at-tji-twitterusername-hongsupshin-githubusername-hongsups”
  content/blog/authors/map-name-hongsup-shin-headshot-https-res-cloudinary-com-texas-justice-initiative-image-upload-v1583374725-hongsup-shin_hmegrv-jpg-biography-volunteer-data-scientist-at-tji-twitterusername-hongsupshin-githubusername-hongsups.md
Labels: netlify-cms/draft

#514 Update Pages “interactive”
  content/interactive.md
Labels: netlify-cms/pending_publish

#515 Update Pages “interactive”
  content/interactive.md
Labels: netlify-cms/pending_publish

#516 Update Pages “interactive”
  content/interactive.md
Labels: netlify-cms/pending_publish

#517 Update Pages “interactive”
  content/interactive.md
Labels: netlify-cms/pending_publish

#519 Update Pages “news”
  content/newsfeed.md
Labels: netlify-cms/pending_publish

#520 Update Components “newContentBanner”
  content/new-content-banner.md
Labels: netlify-cms/pending_review

#521 Update Components “newContentBanner”
  content/new-content-banner.md
Labels: netlify-cms/pending_publish

#523 Update Pages “news”
  content/newsfeed.md
Labels: netlify-cms/pending_publish
